apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uniselec-admin
spec:
  rules:
    - host: uniselec-admin-staging.unilab.edu.br  # Host de staging
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uniselec-admin
                port:
                  number: 80
