apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace padrão (será sobrescrito pelos overlays)
namespace: uniselec-admin

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret-regcred.yaml
  - hpa.yaml

# Variáveis COMUNS
configMapGenerator:
  - name: uniselec-admin-config
    options:
      disableNameSuffixHash: true
    literals:
      - LOG_LEVEL="debug"